version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Resume.pdf
    - images/*
    - styles/*
    - dist/bundle.js